---
- name: "Configurar Nxinx como proxy"
  hosts: localhost
  gather_facts: false
  vars:
    project_root: "{{ playbook_dir }}/../"
    nginx_conf_host: "{{ project_root }}/host_volumes/nginx_conf"
    web_root_host: "{{ project_root }}/host_volumes/web"
    nginx_container: "nginx-proxy"
  
  tasks:
    - name: "Crear directorios en el host"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ nginx_conf_host }}"
        - "{{ web_root_host }}"

    - name: "Copiar index.html"
      ansible.builtin.copy:
        src: "files/index.html"
        dest: "{{ web_root_host }}/index.html"
        mode: '0644'

    - name: "Copiar nginx.conf"
      ansible.builtin.copy:
        src: "templates/nginx.conf"
        dest: "{{ nginx_conf_host }}/nginx.conf"
        mode: '0644'

    - name: "Intentar recargar Nginx"
      ansible.builtin.command: >
        docker exec {{ nginx_container }} nginx -s reload
      register: reload_result
      changed_when: reload_result.rc == 0
      failed_when: false

    - name: "Reiniciar Nginx"
      ansible.builtin.command: >
        docker restart {{ nginx_container }}
      when: reload_result.rc != 0